### PR TITLE
"Use with BossBarAPI as a virion" by @SOF3

### PR DESCRIPTION
**Pull request by inxomnyaa**
- change version
- use virion

### CODE REVIEW

**Comment by inxomnyaa** [comment]
@SOF3 everything correct?

**Comment by SOF3** [comment]
```
--------------------------------------------------------------------------------------------------------------------------------
| Name                                                                  | Size/KB | Type | Created          | Modified         |
--------------------------------------------------------------------------------------------------------------------------------
| plugin.yml                                                            |    0.13 | file | Aug 30, 15:50:19 | Aug 30, 15:50:19 |
| resources/config.yml                                                  |    1.91 | file | Aug 30, 15:50:19 | Aug 30, 15:50:19 |
| src/xenialdan/BossAnnouncement/Main.php                               |    7.99 | file | Aug 30, 15:50:19 | Aug 30, 15:50:19 |
| src/xenialdan/BossAnnouncement/SendTask.php                           |    0.26 | file | Aug 30, 15:50:19 | Aug 30, 15:50:19 |
| src/xenialdan/BossAnnouncement/xenialdan/BossBarAPI/API.php           |    6.76 | file | Aug 30, 15:50:19 | Aug 30, 15:50:19 |
| src/xenialdan/BossAnnouncement/xenialdan/BossBarAPI/BossBarValues.php |    0.63 | file | Aug 30, 15:50:19 | Aug 30, 15:50:19 |
| src/xenialdan/BossAnnouncement/xenialdan/BossBarAPI/SendTask.php      |    0.39 | file | Aug 30, 15:50:19 | Aug 30, 15:50:19 |
| virus-infections.json                                                 |    0.44 | file | Aug 30, 15:50:19 | Aug 30, 15:50:19 |
--------------------------------------------------------------------------------------------------------------------------------
```

You think?

**Comment by inxomnyaa** [comment]
Poggit says its buildt with the BossBarAPI, somehow the files don't appear there i guess?

**Comment by SOF3** [comment]
```
| src/xenialdan/BossAnnouncement/xenialdan/BossBarAPI/API.php           |    6.76 | file | Aug 30, 15:50:19 | Aug 30, 15:50:19 |
| src/xenialdan/BossAnnouncement/xenialdan/BossBarAPI/BossBarValues.php |    0.63 | file | Aug 30, 15:50:19 | Aug 30, 15:50:19 |
| src/xenialdan/BossAnnouncement/xenialdan/BossBarAPI/SendTask.php      |    0.39 | file | Aug 30, 15:50:19 | Aug 30, 15:50:19 |
```
These three files?

**Comment by inxomnyaa** [comment]
@SOF3 Seems alright

**Pull request merged**
